name: ${project.name}
main: wtf.choco.arrows.AlchemicalArrows
version: ${project.version}
description: ${project.description}
author: Choco
softdepend: [ WorldGuard, Alchema ]
api-version: 1.16

commands:
  alchemicalarrows:
    description: The administrative AlchemicalArrows command
    usage: /<command> <clear|version|reload>
    aliases: [aa]
  givearrow:
    description: Give you or another player one of the specialized arrows
    usage: /<command> <arrow> [count] [player]
    aliases: [givearrows]
    permission: alchemicalarrows.command.givearrow
  summonarrow:
    description: Summon an alchemical arrow in the world
    usage: /<command> <arrow> [x] [y] [z] [world] [velocityX] [velocityY] [velocityZ]
    permission: alchemicalarrows.command.summonarrow

permissions:
  alchemicalarrows.worldguard.override:
    description: Override WorldGuard protection for arrows
    default: false

  alchemicalarrows.shoot.*:
    description: Allow the ability to fire every type of arrow available
    default: true
    children:
      alchemicalarrows.shoot.air: true
      alchemicalarrows.shoot.chain: true
      alchemicalarrows.shoot.confusion: true
      alchemicalarrows.shoot.darkness: true
      alchemicalarrows.shoot.death: true
      alchemicalarrows.shoot.earth: true
      alchemicalarrows.shoot.ender: true
      alchemicalarrows.shoot.explosive: true
      alchemicalarrows.shoot.fire: true
      alchemicalarrows.shoot.frost: true
      alchemicalarrows.shoot.grapple: true
      alchemicalarrows.shoot.life: true
      alchemicalarrows.shoot.light: true
      alchemicalarrows.shoot.magic: true
      alchemicalarrows.shoot.magnetic: true
      alchemicalarrows.shoot.necrotic: true
      alchemicalarrows.shoot.water: true

  alchemicalarrows.craft.*:
    description: Allow the ability to craft every type of arrow available
    default: true
    children:
      alchemicalarrows.craft.air: true
      alchemicalarrows.craft.chain: true
      alchemicalarrows.craft.confusion: true
      alchemicalarrows.craft.darkness: true
      alchemicalarrows.craft.death: true
      alchemicalarrows.craft.earth: true
      alchemicalarrows.craft.ender: true
      alchemicalarrows.craft.explosive: true
      alchemicalarrows.craft.fire: true
      alchemicalarrows.craft.frost: true
      alchemicalarrows.craft.grapple: true
      alchemicalarrows.craft.life: true
      alchemicalarrows.craft.light: true
      alchemicalarrows.craft.magic: true
      alchemicalarrows.craft.magnetic: true
      alchemicalarrows.craft.necrotic: true
      alchemicalarrows.craft.water: true

  alchemicalarrows.command.*:
    description: Allow the ability to use all administrative commands
    default: op
    children:
      alchemicalarrows.command.clear: true
      alchemicalarrows.command.reload: true
      alchemicalarrows.command.givearrow: true
      alchemicalarrows.command.summonarrow: true

  # LEGACY PERMISSION NODES: TO BE REMOVED IN A FUTURE RELEASE
  arrows.worldguardoverride:
    description: Override WorldGuard protection for arrows
    default: false

  arrows.shoot.*:
    description: Allow the ability to fire every type of arrow available
    default: true
    children:
      arrows.shoot.air: true
      arrows.shoot.chain: true
      arrows.shoot.confusion: true
      arrows.shoot.darkness: true
      arrows.shoot.death: true
      arrows.shoot.earth: true
      arrows.shoot.ender: true
      arrows.shoot.explosive: true
      arrows.shoot.fire: true
      arrows.shoot.frost: true
      arrows.shoot.grapple: true
      arrows.shoot.life: true
      arrows.shoot.light: true
      arrows.shoot.magic: true
      arrows.shoot.magnetic: true
      arrows.shoot.necrotic: true
      arrows.shoot.water: true

  arrows.craft.*:
    description: Allow the ability to craft every type of arrow available
    default: true
    children:
      arrows.craft.air: true
      arrows.craft.chain: true
      arrows.craft.confusion: true
      arrows.craft.darkness: true
      arrows.craft.death: true
      arrows.craft.earth: true
      arrows.craft.ender: true
      arrows.craft.explosive: true
      arrows.craft.fire: true
      arrows.craft.frost: true
      arrows.craft.grapple: true
      arrows.craft.life: true
      arrows.craft.light: true
      arrows.craft.magic: true
      arrows.craft.magnetic: true
      arrows.craft.necrotic: true
      arrows.craft.water: true

  arrows.command.*:
    description: Allow the ability to use all administrative commands
    default: op
    children:
      arrows.command.clear: true
      arrows.command.reload: true
      arrows.command.givearrow: true
      arrows.command.summonarrow: true
