name: AlchemicalArrows
main: me.choco.arrows.AlchemicalArrows
version: 1.0.2
description: New arrows with special effects when hitting the ground or a player
author: 2008Choco
softdepends: [WorldGuard]
commands:
    alchemicalarrows:
      description: The administrative AlchemicalArrows command
      usage: /<command> <version|reload|killallarrows>
      aliases: [aa]
    givearrow:
      description: Give you or another player one of the specialized arrows
      usage: /<command> <arrow> [count] [player]
      aliases: [givearrows]
permissions:
    arrows.shoot.*:
        description: Allow the ability to fire every type of arrow available
        default: true
        children:
            arrows.shoot.air: true
            arrows.shoot.earth: true
            arrows.shoot.magic: true
            arrows.shoot.ender: true
            arrows.shoot.life: true
            arrows.shoot.death: true
            arrows.shoot.light: true
            arrows.shoot.darkness: true
            arrows.shoot.fire: true
            arrows.shoot.frost: true
            arrows.shoot.water: true
            arrows.shoot.confusion: true
            arrows.shoot.necrotic: true
            arrows.shoot.magnetic: true
    arrows.command.*:
        description: Allow the ability to use all administrative commands
        default: op
        children:
            arrows.command.killallarrows: true
            arrows.command.reload: true
            arrows.command.givearrow: true